// ============================================================
// herald — src/adapters/db/drizzle.ts
// Official Drizzle ORM adapter (PostgreSQL)
//
// Setup: npx herald generate --adapter drizzle
// Then import the generated table objects and pass them here.
// ============================================================

import type {
	HeraldDatabaseAdapter,
	Notification,
	Delivery,
	AuditLog,
	ComplianceExportData,
	ConsentEvent,
	Suppression,
} from "../../types/index.js";
import {
	eq,
	and,
	isNull,
	lt,
	notInArray,
	inArray,
	desc,
	sql,
} from "drizzle-orm";

// The table objects generated by: npx herald generate --adapter drizzle
export interface HeraldDrizzleTables {
	heraldNotifications: any;
	heraldDeliveries: any;
	heraldConsentEvents: any;
	heraldSuppressions: any;
	heraldAuditLogs: any;
}

export interface DrizzleAdapterOptions {
	/**
	 * Resolve the email address for a userId.
	 * Required when using email channel — there is no default user table assumption.
	 *
	 * @example
	 * getUserEmail: (userId) =>
	 *   db.select({ email: users.email })
	 *     .from(users)
	 *     .where(eq(users.id, userId))
	 *     .then(r => r[0]?.email ?? null)
	 */
	getUserEmail?: (userId: string) => Promise<string | null>;
}

let generatedIdSequence = 0;

function createId(): string {
	generatedIdSequence = (generatedIdSequence + 1) % Number.MAX_SAFE_INTEGER;
	return [
		Date.now().toString(36).padStart(10, "0"),
		generatedIdSequence.toString(36).padStart(8, "0"),
		crypto.randomUUID(),
	].join("_");
}

function resultRows<T = unknown>(result: unknown): T[] {
	if (Array.isArray(result)) return result as T[];
	if (
		result &&
		typeof result === "object" &&
		Array.isArray((result as { rows?: unknown }).rows)
	) {
		return (result as { rows: T[] }).rows;
	}
	return [];
}

function dateOrNull(value: unknown): Date | null {
	if (value == null) return null;
	return value instanceof Date ? value : new Date(String(value));
}

export function createDrizzleAdapter(
	db: any, // Drizzle DB instance
	tables: HeraldDrizzleTables,
	opts: DrizzleAdapterOptions = {},
): HeraldDatabaseAdapter {
	const {
		heraldNotifications: notif,
		heraldDeliveries: deliv,
		heraldConsentEvents: consentEvents,
		heraldSuppressions: suppressions,
		heraldAuditLogs: audit,
	} = tables;

	return {
		// ── Notifications ─────────────────────────────────────────

		async createNotification(data) {
			const id = createId();
			const rows = await db
				.insert(notif)
				.values({ id, ...data, createdAt: new Date() })
				.returning();
			return rows[0] as Notification;
		},

		async getNotifications(userId, opts = {}) {
			return db
				.select()
				.from(notif)
				.where(eq(notif.userId, userId))
				.orderBy(desc(notif.createdAt), desc(notif.id))
				.limit(opts.limit ?? 20)
				.offset(opts.offset ?? 0) as Promise<Notification[]>;
		},

		async getUnreadNotifications(userId) {
			return db
				.select()
				.from(notif)
				.where(and(eq(notif.userId, userId), isNull(notif.readAt)))
				.orderBy(desc(notif.createdAt), desc(notif.id)) as Promise<
				Notification[]
			>;
		},

		async countUnread(userId) {
			const result = await db
				.select({ count: sql<number>`count(*)::int` })
				.from(notif)
				.where(and(eq(notif.userId, userId), isNull(notif.readAt)));
			return result[0]?.count ?? 0;
		},

		async markRead(notificationId) {
			await db
				.update(notif)
				.set({ readAt: new Date() })
				.where(eq(notif.id, notificationId));
		},

		async markAllRead(userId) {
			await db
				.update(notif)
				.set({ readAt: new Date() })
				.where(and(eq(notif.userId, userId), isNull(notif.readAt)));
		},

		async getNotificationByDeliveryId(deliveryId) {
			const rows = await db
				.select()
				.from(notif)
				.where(eq(notif.deliveryId, deliveryId))
				.limit(1);
			return (rows[0] ?? null) as Notification | null;
		},

		// ── Deliveries ────────────────────────────────────────────

		async createDelivery(data) {
			const now = new Date();
			const id = createId();
			const rows = await db
				.insert(deliv)
				.values({
					id,
					...data,
					bypassComplianceCheck: data.bypassComplianceCheck ?? false,
					createdAt: now,
					updatedAt: now,
				})
				.returning();
			return rows[0] as Delivery;
		},

		async createDeliveryIdempotent(data, reusableStatuses) {
			const createFresh = async (executor: typeof db) => {
				const now = new Date();
				const id = createId();
				const rows = await executor
					.insert(deliv)
					.values({
						id,
						...data,
						bypassComplianceCheck: data.bypassComplianceCheck ?? false,
						createdAt: now,
						updatedAt: now,
					})
					.returning();
				return { delivery: rows[0] as Delivery, created: true };
			};
			if (!data.idempotencyKey) return createFresh(db);
			return db.transaction(async (tx: typeof db) => {
				await tx.execute(sql`set transaction isolation level serializable`);
				const existingRows = await tx
					.select()
					.from(deliv)
					.where(
						and(
							eq(deliv.idempotencyKey, data.idempotencyKey),
							inArray(deliv.status, [...reusableStatuses]),
						),
					)
					.orderBy(desc(deliv.updatedAt), desc(deliv.createdAt), desc(deliv.id))
					.limit(1);
				if (existingRows[0]) {
					return { delivery: existingRows[0] as Delivery, created: false };
				}
				return createFresh(tx);
			});
		},

		async updateDelivery(id, data) {
			const rows = await db
				.update(deliv)
				.set({ ...data, updatedAt: new Date() })
				.where(eq(deliv.id, id))
				.returning();
			return rows[0] as Delivery;
		},

		async getDelivery(id) {
			const rows = await db
				.select()
				.from(deliv)
				.where(eq(deliv.id, id))
				.limit(1);
			return (rows[0] ?? null) as Delivery | null;
		},

		async getDeliveryByIdempotencyKey(key) {
			const reusableRows = await db
				.select()
				.from(deliv)
				.where(
					and(
						eq(deliv.idempotencyKey, key),
						inArray(deliv.status, [
							"pending",
							"scheduled",
							"claimed",
							"dispatched",
							"retrying",
							"accepted",
						]),
					),
				)
				.orderBy(desc(deliv.updatedAt), desc(deliv.createdAt), desc(deliv.id))
				.limit(1);
			return (reusableRows[0] ?? null) as Delivery | null;
		},

		async getDeliveriesByUser(userId, opts = {}) {
			return db
				.select()
				.from(deliv)
				.where(eq(deliv.userId, userId))
				.orderBy(desc(deliv.createdAt), desc(deliv.id))
				.limit(opts.limit ?? 20)
				.offset(opts.offset ?? 0) as Promise<Delivery[]>;
		},

		// ── Compliance evidence ───────────────────────────────────

		async createConsentEvent(data) {
			const rows = await db
				.insert(consentEvents)
				.values({
					id: createId(),
					...data,
					subjectType: data.subjectType ?? null,
					formId: data.formId ?? null,
					legalNoticeVersionId: data.legalNoticeVersionId ?? null,
					privacyPolicyVersion: data.privacyPolicyVersion ?? null,
					checkboxTextVersion: data.checkboxTextVersion ?? null,
					ipHash: data.ipHash ?? null,
					userAgentHash: data.userAgentHash ?? null,
					metadata: data.metadata ?? null,
					createdAt: data.createdAt ?? new Date(),
				})
				.returning();
			return rows[0] as ConsentEvent;
		},

		async getConsentEvents(input) {
			const conditions = [eq(consentEvents.subjectId, input.subjectId)];
			if (input.channel)
				conditions.push(eq(consentEvents.channel, input.channel));
			if (input.purpose)
				conditions.push(eq(consentEvents.purpose, input.purpose));
			return db
				.select()
				.from(consentEvents)
				.where(and(...conditions))
				.orderBy(
					desc(consentEvents.createdAt),
					desc(consentEvents.id),
				) as Promise<ConsentEvent[]>;
		},

		async createSuppression(data) {
			const rows = await db
				.insert(suppressions)
				.values({
					id: createId(),
					...data,
					purpose: data.purpose ?? null,
					source: data.source ?? null,
					createdAt: data.createdAt ?? new Date(),
				})
				.returning();
			return rows[0] as Suppression;
		},

		async findSuppression(input) {
			if (input.purpose != null) {
				const specific = await db
					.select()
					.from(suppressions)
					.where(
						and(
							eq(suppressions.addressHash, input.addressHash),
							eq(suppressions.channel, input.channel),
							eq(suppressions.purpose, input.purpose),
						),
					)
					.orderBy(desc(suppressions.createdAt), desc(suppressions.id))
					.limit(1);
				if (specific[0]) return specific[0] as Suppression;
			}
			const global = await db
				.select()
				.from(suppressions)
				.where(
					and(
						eq(suppressions.addressHash, input.addressHash),
						eq(suppressions.channel, input.channel),
						isNull(suppressions.purpose),
					),
				)
				.orderBy(desc(suppressions.createdAt), desc(suppressions.id))
				.limit(1);
			return (global[0] ?? null) as Suppression | null;
		},

		// ── Audit log ─────────────────────────────────────────────

		async createAuditLog(data) {
			const rows = await db
				.insert(audit)
				.values({ id: createId(), ...data, createdAt: new Date() })
				.returning();
			return rows[0] as AuditLog;
		},

		async getAuditLogs(userId, opts = {}) {
			return db
				.select()
				.from(audit)
				.where(eq(audit.userId, userId))
				.orderBy(desc(audit.createdAt), desc(audit.id))
				.limit(opts.limit ?? 50) as Promise<AuditLog[]>;
		},

		// ── Compliance lifecycle ─────────────────────────────────

		async eraseSubject(userId) {
			const erasedId = `erased_${crypto.randomUUID()}`;
			const now = new Date();

			// Compute SHA-256 hash of userId for audit log (no PII stored)
			let userIdHash: string;
			if (typeof globalThis.crypto !== "undefined") {
				const encoder = new TextEncoder();
				const data = encoder.encode(userId);
				const hash = await globalThis.crypto.subtle.digest("SHA-256", data);
				userIdHash = Array.from(new Uint8Array(hash))
					.map((b) => b.toString(16).padStart(2, "0"))
					.join("");
			} else {
				/* v8 ignore next 2 */
				const { createHash } = await import("crypto");
				userIdHash = createHash("sha256").update(userId).digest("hex");
			}

			await db.transaction(async (tx: any) => {
				// Anonymize deliveries and scrub userId from scoped idempotency keys.
				await tx
					.update(deliv)
					.set({
						userId: erasedId,
						idempotencyKey: sql`CASE WHEN ${deliv.idempotencyKey} IS NULL THEN NULL ELSE replace(${deliv.idempotencyKey}, ${userId}, ${userIdHash}) END`,
					})
					.where(eq(deliv.userId, userId));

				// Anonymize notifications
				await tx
					.update(notif)
					.set({
						userId: erasedId,
						title: "[redacted]",
						body: "[redacted]",
						data: null,
						href: null,
					})
					.where(eq(notif.userId, userId));

				// Anonymize append-only consent evidence with a stable hash for audit cross-reference.
				await tx
					.update(consentEvents)
					.set({ subjectId: userIdHash })
					.where(eq(consentEvents.subjectId, userId));

				// Anonymize existing audit logs with the same stable hash.
				await tx
					.update(audit)
					.set({ userId: userIdHash })
					.where(eq(audit.userId, userId));

				// Audit log inside transaction — rolls back on any failure
				await tx.insert(audit).values({
					id: createId(),
					userId: userIdHash,
					action: "compliance.erase",
					metadata: { userIdHash, erasedAt: now.toISOString() },
					createdAt: now,
				});
			});
		},

		async exportUser(userId) {
			const [notifications, deliveries, consentEventsRows, auditLogs] =
				await Promise.all([
					db
						.select()
						.from(notif)
						.where(eq(notif.userId, userId))
						.orderBy(desc(notif.createdAt), desc(notif.id)),
					db
						.select()
						.from(deliv)
						.where(eq(deliv.userId, userId))
						.orderBy(desc(deliv.createdAt), desc(deliv.id)),
					db
						.select()
						.from(consentEvents)
						.where(eq(consentEvents.subjectId, userId))
						.orderBy(desc(consentEvents.createdAt), desc(consentEvents.id)),
					db
						.select()
						.from(audit)
						.where(eq(audit.userId, userId))
						.orderBy(desc(audit.createdAt), desc(audit.id)),
				]);

			return {
				userId,
				exportedAt: new Date(),
				notifications,
				deliveries,
				consentEvents: consentEventsRows,
				// Suppressions are address-hash scoped, not subject-scoped.
				suppressions: [],
				auditLogs,
			} as ComplianceExportData;
		},

		async claimScheduledBatch(before, workerId, limit, leaseMs) {
			// Atomic claim via raw SQL: lock ordered candidates first, then assign
			// ordinals separately because PostgreSQL rejects FOR UPDATE with windows.
			const result = await db.execute(sql`
        WITH locked_candidates AS (
          SELECT id, scheduled_at FROM ${deliv}
          WHERE
            (status = 'scheduled' AND scheduled_at <= ${before})
            OR (status = 'claimed' AND claim_expires_at < NOW())
          ORDER BY scheduled_at ASC, id DESC
          LIMIT ${limit}
          FOR UPDATE SKIP LOCKED
        ), candidates AS (
          SELECT
            id,
            row_number() OVER (ORDER BY scheduled_at ASC, id DESC) AS claim_order
          FROM locked_candidates
        ), updated AS (
          UPDATE ${deliv}
          SET
            status = 'claimed',
            claimed_at = NOW(),
            claim_expires_at = NOW() + (${leaseMs} * INTERVAL '1 millisecond'),
            claimed_by = ${workerId},
            updated_at = NOW()
          WHERE id IN (SELECT id FROM candidates)
          RETURNING *
        )
        SELECT updated.*
        FROM updated
        JOIN candidates ON candidates.id = updated.id
        ORDER BY candidates.claim_order ASC
      `);
			return resultRows<any>(result).map((row: any) => ({
				id: row.id,
				userId: row.user_id,
				eventType: row.event_type,
				templateName: row.template_name,
				channel: row.channel,
				status: row.status,
				attempts: row.attempts ?? 0,
				lastError: row.last_error ?? null,
				externalId: row.external_id ?? null,
				idempotencyKey: row.idempotency_key ?? null,
				scheduledAt: row.scheduled_at ?? null,
				acceptedAt: row.accepted_at ?? null,
				failedAt: row.failed_at ?? null,
				claimedAt: dateOrNull(row.claimed_at),
				claimExpiresAt: dateOrNull(row.claim_expires_at),
				claimedBy: row.claimed_by ?? null,
				resolveAttempts: row.resolve_attempts ?? 0,
				bypassComplianceCheck: row.bypass_compliance_check ?? null,
				queueJobId: row.queue_job_id ?? null,
				addressHash: row.address_hash ?? null,
				sideEffectsCompletedAt: row.side_effects_completed_at ?? null,
				renderedHash: row.rendered_hash ?? null,
				purpose: row.purpose ?? null,
				legalBasisAtSend: row.legal_basis_at_send ?? null,
				consentEventId: row.consent_event_id ?? null,
				suppressionId: row.suppression_id ?? null,
				complianceEvidenceId: row.compliance_evidence_id ?? null,
				complianceRequired: row.compliance_required ?? null,
				complianceRequiresConsentEvent:
					row.compliance_requires_consent_event ?? null,
				complianceRequiresSuppressionCheck:
					row.compliance_requires_suppression_check ?? null,
				complianceRequiresEvidence: row.compliance_requires_evidence ?? null,
				complianceDefaultDecision: row.compliance_default_decision ?? null,
				complianceDecision: row.compliance_decision ?? null,
				complianceCheckedAt: row.compliance_checked_at ?? null,
				createdAt: dateOrNull(row.created_at)!,
				updatedAt: dateOrNull(row.updated_at)!,
			})) as Delivery[];
		},

		async cancelScheduledDeliveries(userId) {
			const result = await db.execute(sql`
        UPDATE ${deliv}
        SET status = 'redacted', updated_at = NOW()
        WHERE user_id = ${userId}
          AND status IN ('scheduled', 'claimed')
        RETURNING id, queue_job_id
      `);
			return resultRows<any>(result).map((r: any) => ({
				id: r.id as string,
				queueJobId: (r.queue_job_id ?? null) as string | null,
			}));
		},

		async findAuditLogByAction(userId, action) {
			const rows = await db
				.select()
				.from(audit)
				.where(and(eq(audit.userId, userId), eq(audit.action, action)))
				.orderBy(desc(audit.createdAt), desc(audit.id))
				.limit(1);
			return (rows[0] as AuditLog | undefined) ?? null;
		},

		async purgeExpiredDeliveries(olderThan) {
			const result = await db
				.delete(deliv)
				.where(
					and(
						lt(deliv.createdAt, olderThan),
						notInArray(deliv.status, ["scheduled", "claimed", "retrying"]),
					),
				)
				.returning({ id: deliv.id });
			return result.length;
		},

		async purgeExpiredAuditLogs(olderThan) {
			const result = await db
				.delete(audit)
				.where(lt(audit.createdAt, olderThan))
				.returning({ id: audit.id });
			return result.length;
		},

		// ── User resolution ───────────────────────────────────────

		async getUserEmail(userId) {
			if (opts.getUserEmail) return opts.getUserEmail(userId);
			throw new Error(
				"[herald] Drizzle adapter: getUserEmail not configured. " +
					"Pass it as the third argument to createDrizzleAdapter().\n" +
					"Example: createDrizzleAdapter(db, tables, {\n" +
					"  getUserEmail: (id) => db.select({ email: users.email })\n" +
					"    .from(users).where(eq(users.id, id)).then(r => r[0]?.email ?? null)\n" +
					"})",
			);
		},
	};
}
